#!/bin/bash

database_environment_init(){
	EMPTY_DB=$(mktemp)

	printf "environment: Initializing empty database for reset source at %s\n" "$EMPTY_DB"
	printf "export CMAIL_TEST_EMPTY_MASTER=\"%s\"\n" "$EMPTY_DB" >> "$TEST_MARKER_FILE"
	cat ../../sql-update/install_master.sql | sqlite3 "$EMPTY_DB"
}

if [ -z "$CMAIL_TEST_ENVIRONMENT_OK" ]; then
	return
fi

database_reset(){
	cp "$CMAIL_TEST_EMPTY_MASTER" "$CMAIL_TEST_PRODUCTIVE_MASTER"
	printf "harness: Master database reset\n"
}
