#!/usr/bin/expect -f
spawn sqlite3 -csv $::env(CMAIL_TEST_PRODUCTIVE_MASTER)
set database $spawn_id

send_user "Spawned database shell on $database\n"

expect {
	-i $database "SQLite version 3" {
	}
	default {
		send_user "Invalid database version (need sqlite3)\n"
		exit 1
	}
}

expect {
	-i $database "sqlite>" {
	}
	default {
		send_user "No prompt received\n"
		exit 1	
	}
}

send -i $database "PRAGMA foreign_keys = ON;\r"
expect {
	-i $database "sqlite>" {
	}
	default {
		send_user "Failed to enable foreign key support\n"
		exit 1
	}
}
