#!/usr/bin/expect -f
spawn gnutls-cli --crlf --starttls --insecure --port $::env(SMTP_PORT) $::env(SMTP_HOST)

set smtp $spawn_id

send_user "Spawned SMTP connection on $smtp\n"

expect {
	-i $smtp "220 " {
	}
	timeout {
		send_user "SMTP server failed to respond\n"
		exit 1
	}
}
