#!/bin/sh

cmail-smtpd /etc/cmail/smtpd.conf
cmail-dispatchd /etc/cmail/dispatchd.conf 
cmail-popd /etc/cmail/popd.conf

while true; do
	PROCS=$(ps aux | grep cmail-)
	if [ "$PROCS" -lt "3" ]; then
		exit 1
	fi
	sleep 5
done
