Document: cmail-mta
Title: Debian cmail-mta Manual
Author: <insert document author here>
Abstract: This manual describes what cmail-mta is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cmail-mta/cmail-mta.sgml.gz

Format: postscript
Files: /usr/share/doc/cmail-mta/cmail-mta.ps.gz

Format: text
Files: /usr/share/doc/cmail-mta/cmail-mta.text.gz

Format: HTML
Index: /usr/share/doc/cmail-mta/html/index.html
Files: /usr/share/doc/cmail-mta/html/*.html
